# Generated by Django 3.1.7 on 2021-03-09 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Status',
        ),
    ]
