# Generated by Django 3.1.7 on 2021-03-18 10:38

from django.db import migrations, models
import webapp


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20210318_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracer',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, validators=[
                webapp.validator.Validator(['%', '@', '&'])], verbose_name='Полное описание'),
        ),
    ]
