# Generated by Django 3.1.7 on 2021-03-26 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_tracer_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracer',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracers', to='webapp.project', verbose_name='Проект'),
        ),
    ]
