# Generated by Django 3.1.7 on 2021-04-14 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_project_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('add_delete_change', 'добавлять,удалять,изменять')]},
        ),
    ]
