# Generated by Django 3.1.7 on 2021-04-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bird_date',
            new_name='birth_date',
        ),
    ]
